#!/usr/bin/env bash

hour=`date +%H`
if [[ $hour -le 6 || $hour -ge 18 ]]; then
    time='night'
elif [[ $hour -gt 6 && $hour -lt 12 ]]; then
    time='morning'
elif [[ $hour -ge 12 && $hour -lt 18 ]]; then
    time='afternoon' 
fi


ZIPCODE=$1
OWM_APIKEY=$2
weather_condition=`http GET http://api.openweathermap.org/data/2.5/weather zip==$ZIPCODE appid==$OWM_APIKEY | jq '.weather' | jq '.[0].main' | sed 's/^.//;s/.$//'`

case $weather_condition in
    "Clear" | "Snow")
        wallpaper_name=clear
        ;;
    "Thunderstorm" | "Drizzle" | "Rain")
        wallpaper_name=rainy
        ;;
    "Clouds" | "Atmosphere")
        wallpaper_name=cloudy
        ;;
    *)
        wallpaper_name=
        ;;
esac


wallpaper_name="${wallpaper_name}_${time}"
echo `fd $wallpaper_name`
